language: node_js
node_js:
- '4'
- '6'

cache:
  directories:
  - node_modules

deploy:
  provider: npm
  email: open-source@goodeggs.com
  api_key:
    secure: "7xdQXAAKB4bkI/5MXAe34KoXREAL8CiXoZsukDIdJKs7Lh7ZVN3A/qVHIwFy/19LJnz2G+ZU8cte1tJ2/OqJMrPDz48brTzB6C0y6Ow1jusoM1y8tqS57UFqlIjpJ3nMHtbNl2wKpTO9ctwqDU7PcDTQjMjUqfL5sFxW7VruXrPzh66iKNHlXhrDCvF6kmSxE53agtc6dLQKfoblJeWAc87NF01YYn4ELozTVBrNb/y3qBc4eskMb28HWh9gthJr2D8uH9x4kSAy680vwlSnAxSYUHqfku5kOdl/Xto1afPBAgR4udWDwqlHuuC+0MA37NLOdhPdKwHmOSiytyKiKkfpkuuJCnNAK+FD9fyfVqk0uHCeyJBwiSmZ5gQmMSNm/lwEkVs+2TuyuRP8WgDSQd/5N1xxMiQuRMBdWNQHT1b0uSl9x6cMsjuyzs1aybTMHVcxEaWdPvmWhwmEkLWjkL3o1+CfSNcTsYZCaRD5S3jbguNA8mLg/7PIt43jt5QpSYH4hCAfQUO7XRM/GK5/pq6fnGwNp7M/wxPw2eOtQDOAU/R6lj9slF4gu8ovrbZ54dHVqI8NuuzJ+urHqCEwlXXhlLnpho4Wq9+SEl3tGardM7bwctojZ6QK/dp9CvrvClJVYxVBIoLXKIKS0pr5vpycf9WNqd/YQ564ycq7W6g="
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    node: '4'

